### PR TITLE
SonarBranch

### PR DESCRIPTION
**Pull request by shajiBS24**
Verify my program to merge...

### CODE REVIEW

**Review by Purushothaman1962 — COMMENTED** [review]
Shaji kindly verify in LMSController.java modify the methods name (first letter to be small) like PerformInsert to performInsert and remove the unused 2nd import statement of Array list.

**Comment by shajiBS24** [comment]
I have resolved it. So Kindly, verify it again.

**Comment by Purushothaman1962** [comment]
Ok fine. Now you can merge it.

**Comment by shajiBS24** [comment]
Thank you for reviewing my project.

**Pull request merged**
